### PR TITLE
Fix All AS3 DisplayObject Getters/Setters

### PR DESCRIPTION
**Pull request by Fancy2209**

### CODE REVIEW

**Comment by joshtynjala** [comment]
@Fancy2209 I just realized... in #3, you modified openfl/display/DisplayObject.as, but in #4, you modified flash/display/DisplayObject.as. Both files should probably include the full set of changes to all properties.

**Comment by Fancy2209** [comment]
> @Fancy2209 I just realized... in #3, you modified openfl/display/DisplayObject.as, but in #4, you modified flash/display/DisplayObject.as. Both files should probably include the full set of changes to all properties.

I just realized the same looking in jpexs. Just made #5
By the way, why is the flash package even a thing? it causes issues 
imagem

**Comment by joshtynjala** [comment]
> By the way, why is the flash package even a thing?

Presumably, so that you can re-use existing code without changing all of the imports from flash to openfl.

Relatedly, in the Haxelib version, Lime/OpenFL automatically adds `--remap flash:openfl` to the generated .hxml file. Same idea.

**Comment by Fancy2209** [comment]
I remember trying it and it gave a implicit coercion or something of the sort

**Comment by joshtynjala** [comment]
> I remember trying it and it gave a implicit coercion or something of the sort

Yeah, that makes sense. AS3 wouldn't have any reason to believe that openfl.display.DisplayObject is related to flash.display.DisplayObject. With this in mind, the `flash` package externs should probably be removed at some point.

**Pull request merged**
